export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const GET_REGIONS_REQUEST = 'GET_REGIONS_REQUEST';
export const GET_REGIONS_SUCCESS = 'GET_REGIONS_SUCCESS';
export const GET_REGIONS_FAILURE = 'GET_REGIONS_FAILURE';

export const GET_BUS_GROUP_REQUEST = 'GET_BUS_GROUP_REQUEST';
export const GET_BUS_GROUP_SUCCESS = 'GET_BUS_GROUP_SUCCESS';
export const GET_BUS_GROUP_FAILURE = 'GET_BUS_GROUP_FAILURE';

export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';

export const FETCH_FLEET_REPORT_REQUEST = 'FETCH_FLEET_REPORT_REQUEST';
export const FETCH_FLEET_REPORT_SUCCESS = 'FETCH_FLEET_REPORT_SUCCESS';
export const FETCH_FLEET_REPORT_FAILURE = 'FETCH_FLEET_REPORT_FAILURE';

export const FETCH_VIOLATION_VEH_WISE_REPORT_REQUEST =
  'FETCH_VIOLATION_VEH_WISE_REPORT_REQUEST';
export const FETCH_VIOLATION_VEH_WISE_REPORT_SUCCESS =
  'FETCH_VIOLATION_VEH_WISE_REPORT_SUCCESS';
export const FETCH_VIOLATION_VEH_WISE_REPORT_FAILURE =
  'FETCH_VIOLATION_VEH_WISE_REPORT_FAILURE';

export const FETCH_VIOLATION_DAY_WISE_REPORT_REQUEST =
  'FETCH_VIOLATION_DAY_WISE_REPORT_REQUEST';
export const FETCH_VIOLATION_DAY_WISE_REPORT_SUCCESS =
  'FETCH_VIOLATION_DAY_WISE_REPORT_SUCCESS';
export const FETCH_VIOLATION_DAY_WISE_REPORT_FAILURE =
  'FETCH_VIOLATION_DAY_WISE_REPORT_FAILURE';

export const FETCH_VIOLATION_TIME_WISE_REPORT_REQUEST =
  'FETCH_VIOLATION_TIME_WISE_REPORT_REQUEST';
export const FETCH_VIOLATION_TIME_WISE_REPORT_SUCCESS =
  'FETCH_VIOLATION_TIME_WISE_REPORT_SUCCESS';
export const FETCH_VIOLATION_TIME_WISE_REPORT_FAILURE =
  'FETCH_VIOLATION_TIME_WISE_REPORT_FAILURE';

export const FETCH_SPEED_VIOLATION_REPORT_REQUEST =
  'FETCH_SPEED_VIOLATION_REPORT_REQUEST';
export const FETCH_SPEED_VIOLATION_REPORT_SUCCESS =
  'FETCH_SPEED_VIOLATION_REPORT_SUCCESS';
export const FETCH_SPEED_VIOLATION_REPORT_FAILURE =
  'FETCH_SPEED_VIOLATION_REPORT_FAILURE';

export const POST_LTO_STATS_REQUEST = 'POST_LTO_STATS_REQUEST';
export const POST_LTO_STATS_SUCCESS = 'POST_LTO_STATS_SUCCESS';
export const POST_LTO_STATS_FAILURE = 'POST_LTO_STATS_FAILURE';

export const POST_VEHICLES_STATS_REQUEST = 'POST_VEHICLES_STATS_REQUEST';
export const POST_VEHICLES_STATS_SUCCESS = 'POST_VEHICLES_STATS_SUCCESS';
export const POST_VEHICLES_STATS_FAILURE = 'POST_VEHICLES_STATS_FAILURE';

export const POST_DDC_STATS_REQUEST = 'POST_DDC_STATS_REQUEST';
export const POST_DDC_STATS_SUCCESS = 'POST_DDC_STATS_SUCCESS';
export const POST_DDC_STATS_FAILURE = 'POST_DDC_STATS_FAILURE';

export const POST_EMP_TRAINING_STATS_REQUEST =
  'POST_EMP_TRAINING_STATS_REQUEST';
export const POST_EMP_TRAINING_STATS_SUCCESS =
  'POST_EMP_TRAINING_STATS_SUCCESS';
export const POST_EMP_TRAINING_STATS_FAILURE =
  'POST_EMP_TRAINING_STATS_FAILURE';

export const POST_DOCUMENTS_STATUS_REQUEST = 'POST_DOCUMENTS_STATUS_REQUEST';
export const POST_DOCUMENTS_STATUS_SUCCESS = 'POST_DOCUMENTS_STATUS_SUCCESS';
export const POST_DOCUMENTS_STATUS_FAILURE = 'POST_DOCUMENTS_STATUS_FAILURE';

export const GET_ALL_REGIONS_REQUEST = 'GET_ALL_REGIONS_REQUEST';
export const GET_ALL_REGIONS_SUCCESS = 'GET_ALL_REGIONS_SUCCESS';
export const GET_ALL_REGIONS_FAILURE = 'GET_ALL_REGIONS_FAILURE';

export const GET_ALL_GROUP_REQUEST = 'GET_ALL_GROUP_REQUEST';
export const GET_ALL_GROUP_SUCCESS = 'GET_ALL_GROUP_SUCCESS';
export const GET_ALL_GROUP_FAILURE = 'GET_ALL_GROUP_FAILURE';

export const GET_USER_DETAIL_REQUEST = 'GET_USER_DETAIL_REQUEST';
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';
export const GET_USER_DETAIL_FAILURE = 'GET_USER_DETAIL_FAILURE';

export const GET_DASHBOARD_COUNTERS_REQUEST = 'GET_DASHBOARD_COUNTERS_REQUEST';
export const GET_DASHBOARD_COUNTERS_SUCCESS = 'GET_DASHBOARD_COUNTERS_SUCCESS';
export const GET_DASHBOARD_COUNTERS_FAILURE = 'GET_DASHBOARD_COUNTERS_FAILURE';

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

export const GET_USER_PROFILES_REQUEST = 'GET_USER_PROFILES_REQUEST';
export const GET_USER_PROFILES_SUCCESS = 'GET_USER_PROFILES_SUCCESS';
export const GET_USER_PROFILES_FAILURE = 'GET_USER_PROFILES_FAILURE';

export const PUT_UPDATE_PROFILE_REQUEST = 'PUT_UPDATE_PROFILE_REQUEST';
export const PUT_UPDATE_PROFILE_SUCCESS = 'PUT_UPDATE_PROFILE_SUCCESS';
export const PUT_UPDATE_PROFILE_FAILURE = 'PUT_UPDATE_PROFILE_FAILURE';

export const FETCH_INDIVIDUAL_BLACKPOINTS_REQUEST =
  'FETCH_INDIVIDUAL_BLACKPOINTS_REQUEST';
export const FETCH_INDIVIDUAL_BLACKPOINTS_SUCCESS =
  'FETCH_INDIVIDUAL_BLACKPOINTS_SUCCESS';
export const FETCH_INDIVIDUAL_BLACKPOINTS_FAILURE =
  'FETCH_INDIVIDUAL_BLACKPOINTS_FAILURE';

export const FETCH_ALL_BLACKPOINTS_REQUEST = 'FETCH_ALL_BLACKPOINTS_REQUEST';
export const FETCH_ALL_BLACKPOINTS_SUCCESS = 'FETCH_ALL_BLACKPOINTS_SUCCESS';
export const FETCH_ALL_BLACKPOINTS_FAILURE = 'FETCH_ALL_BLACKPOINTS_FAILURE';

export const FETCH_VIOLATIONS_RIGHT_NOW_REQUEST =
  'FETCH_VIOLATIONS_RIGHT_NOW_REQUEST';
export const FETCH_VIOLATIONS_RIGHT_NOW_SUCCESS =
  'FETCH_VIOLATIONS_RIGHT_NOW_SUCCESS';
export const FETCH_VIOLATIONS_RIGHT_NOW_FAILURE =
  'FETCH_VIOLATIONS_RIGHT_NOW_FAILURE';

export const FETCH_TOP_FIVE_DRIVERS_REQUEST = 'FETCH_TOP_FIVE_DRIVERS_REQUEST';
export const FETCH_TOP_FIVE_DRIVERS_SUCCESS = 'FETCH_TOP_FIVE_DRIVERS_SUCCESS';
export const FETCH_TOP_FIVE_DRIVERS_FAILURE = 'FETCH_TOP_FIVE_DRIVERS_FAILURE';

export const FETCH_TOP_FIVE_TRAVELERS_REQUEST =
  'FETCH_TOP_FIVE_TRAVELERS_REQUEST';
export const FETCH_TOP_FIVE_TRAVELERS_SUCCESS =
  'FETCH_TOP_FIVE_TRAVELERS_SUCCESS';
export const FETCH_TOP_FIVE_TRAVELERS_FAILURE =
  'FETCH_TOP_FIVE_TRAVELERS_FAILURE';

export const GET_LTO_REQUEST = 'GET_LTO_REQUEST';
export const GET_LTO_SUCCESS = 'GET_LTO_SUCCESS';
export const GET_LTO_FAILURE = 'GET_LTO_FAILURE';

export const GET_CANCELLED_LTO_REQUEST = 'GET_CANCELLED_LTO_REQUEST';
export const GET_CANCELLED_LTO_SUCCESS = 'GET_CANCELLED_LTO_SUCCESS';
export const GET_CANCELLED_LTO_FAILURE = 'GET_CANCELLED_LTO_FAILURE';

export const GET_VEHICLE_CURRENT_STATUS_REQUEST =
  'GET_VEHICLE_CURRENT_STATUS_REQUEST';
export const GET_VEHICLE_CURRENT_STATUS_SUCCESS =
  'GET_VEHICLE_CURRENT_STATUS_SUCCESS';
export const GET_VEHICLE_CURRENT_STATUS_FAILURE =
  'GET_VEHICLE_CURRENT_STATUS_FAILURE';

export const GET_VEHICLE_REG_NO_REQUEST = 'GET_VEHICLE_REG_NO_REQUEST';
export const GET_VEHICLE_REG_NO_SUCCESS = 'GET_VEHICLE_REG_NO_SUCCESS';
export const GET_VEHICLE_REG_NO_FAILURE = 'GET_VEHICLE_REG_NO_FAILURE';

export const FETCH_LATE_NIGHT_EXIT_REPORT_REQUEST =
  'FETCH_LATE_NIGHT_EXIT_REPORT_REQUEST';
export const FETCH_LATE_NIGHT_EXIT_REPORT_SUCCESS =
  'FETCH_LATE_NIGHT_EXIT_REPORT_SUCCESS';
export const FETCH_LATE_NIGHT_EXIT_REPORT_FAILURE =
  'FETCH_LATE_NIGHT_EXIT_REPORT_FAILURE';

export const FETCH_TRIP_REPORT_REQUEST = 'FETCH_TRIP_REPORT_REQUEST';
export const FETCH_TRIP_REPORT_SUCCESS = 'FETCH_TRIP_REPORT_SUCCESS';
export const FETCH_TRIP_REPORT_FAILURE = 'FETCH_TRIP_REPORT_FAILURE';

export const FETCH_VEHICLE_INSPECTION_REPORT_REQUEST =
  'FETCH_VEHICLE_INSPECTION_REPORT_REQUEST';
export const FETCH_VEHICLE_INSPECTION_REPORT_SUCCESS =
  'FETCH_VEHICLE_INSPECTION_REPORT_SUCCESS';
export const FETCH_VEHICLE_INSPECTION_REPORT_FAILURE =
  'FETCH_VEHICLE_INSPECTION_REPORT_FAILURE';

export const FETCH_DRIVING_OBSERVATIONS_REPORT_REQUEST =
  'FETCH_DRIVING_OBSERVATIONS_REPORT_REQUEST';
export const FETCH_DRIVING_OBSERVATIONS_REPORT_SUCCESS =
  'FETCH_DRIVING_OBSERVATIONS_REPORT_SUCCESS';
export const FETCH_DRIVING_OBSERVATIONS_REPORT_FAILURE =
  'FETCH_DRIVING_OBSERVATIONS_REPORT_FAILURE';

export const FETCH_VEHICLES_MONTHLY_MILEAGE_REPORT_REQUEST =
  'FETCH_VEHICLES_MONTHLY_MILEAGE_REPORT_REQUEST';
export const FETCH_VEHICLES_MONTHLY_MILEAGE_REPORT_SUCCESS =
  'FETCH_VEHICLES_MONTHLY_MILEAGE_REPORT_SUCCESS';
export const FETCH_VEHICLES_MONTHLY_MILEAGE_REPORT_FAILURE =
  'FETCH_VEHICLES_MONTHLY_MILEAGE_REPORT_FAILURE';

export const SAVE_VEHICLE_OBSERVATION_REQUEST =
  'SAVE_VEHICLE_OBSERVATION_REQUEST';
export const SAVE_VEHICLE_OBSERVATION_SUCCESS =
  'SAVE_VEHICLE_OBSERVATION_SUCCESS';
export const SAVE_VEHICLE_OBSERVATION_FAILURE =
  'SAVE_VEHICLE_OBSERVATION_FAILURE';

export const SAVE_DRIVING_OBSERVATION_REQUEST =
  'SAVE_DRIVING_OBSERVATION_REQUEST';
export const SAVE_DRIVING_OBSERVATION_SUCCESS =
  'SAVE_DRIVING_OBSERVATION_SUCCESS';
export const SAVE_DRIVING_OBSERVATION_FAILURE =
  'SAVE_DRIVING_OBSERVATION_FAILURE';

export const GET_AUTHORITY_LETTER_REQUEST = 'GET_AUTHORITY_LETTER_REQUEST';
export const GET_AUTHORITY_LETTER_SUCCESS = 'GET_AUTHORITY_LETTER_SUCCESS';
export const GET_AUTHORITY_LETTER_FAILURE = 'GET_AUTHORITY_LETTER_FAILURE';

export const GET_AUTHORITY_LETTER_FOR_PRINT_REQUEST =
  'GET_AUTHORITY_LETTER_FOR_PRINT_REQUEST';
export const GET_AUTHORITY_LETTER_FOR_PRINT_SUCCESS =
  'GET_AUTHORITY_LETTER_FOR_PRINT_SUCCESS';
export const GET_AUTHORITY_LETTER_FOR_PRINT_FAILURE =
  'GET_AUTHORITY_LETTER_FOR_PRINT_FAILURE';
